@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun May 28 23:36:39 +0900 2023
REM SW Build 3788238 on Tue Feb 21 20:00:34 MST 2023
REM
REM IP Build 3783773 on Tue Feb 21 23:41:56 MST 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim laser_receiver_block_wrapper_behav -key {Behavioral:sim_1:Functional:laser_receiver_block_wrapper} -tclbatch laser_receiver_block_wrapper.tcl -protoinst "protoinst_files/laser_receiver_block.protoinst" -view D:/Project/laser_receiver_project/laser_receiver_block_wrapper_behav.wcfg -log simulate.log"
call xsim  laser_receiver_block_wrapper_behav -key {Behavioral:sim_1:Functional:laser_receiver_block_wrapper} -tclbatch laser_receiver_block_wrapper.tcl -protoinst "protoinst_files/laser_receiver_block.protoinst" -view D:/Project/laser_receiver_project/laser_receiver_block_wrapper_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
